FROM ghcr.io/raonigabriel/coder-core:latest

RUN sudo apk --no-cache add maven gradle

ENV JAVA_HOME=/usr/lib/jvm/default-jvm \
    MAVEN_HOME=/usr/share/java/maven-3 \
    GRADLE_HOME=/usr/share/java/gradle
